version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: trainpassdocker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./SQL/CREATE.sql:/docker-entrypoint-initdb.d/Init.sql
      
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433

  app:
    build: .
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/trainpassdocker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres-data: 